### ISSUE TITLE
ERROR:root:Could not perform read merging with BBmerge

### ISSUE THREAD

**Issue by didietkeren** [USDA-ARS-GBRU/q2_itsxpress#10]
Error when running itsxpress.

ERROR:root:Could not perform read merging with BBmerge. Error from BBmerge was: 
  java -Djava.library.path=/home/didit/miniconda3/envs/qiime2-2020.8/opt/bbmap-38.18/jni/ -ea -Xmx1000m -Xms1000m -cp /home/didit/miniconda3/envs/qiime2-2020.8/opt/bbmap-38.18/current/ jgi.BBMerge in=/tmp/qiime2-archive-qmljhmaa/3b922489-3051-4a70-aabe-bb024f4c70eb/data/FH1_0_L001_R1_001.fastq.gz in2=/tmp/qiime2-archive-qmljhmaa/3b922489-3051-4a70-aabe-bb024f4c70eb/data/FH1_4_L001_R2_001.fastq.gz out=/tmp/itsxpress_j2810rj2/seq.fq.gz t=8 maxmismatches=40 maxratio=0.3
Executing jgi.BBMerge [in=/tmp/qiime2-archive-qmljhmaa/3b922489-3051-4a70-aabe-bb024f4c70eb/data/FH1_0_L001_R1_001.fastq.gz, in2=/tmp/qiime2-archive-qmljhmaa/3b922489-3051-4a70-aabe-bb024f4c70eb/data/FH1_4_L001_R2_001.fastq.gz, out=/tmp/itsxpress_j2810rj2/seq.fq.gz, t=8, maxmismatches=40, maxratio=0.3]
Version 38.18

**Comment by arivers** [comment]
This appears to be a cross post. I've replied to your question here: https://forum.qiime2.org/t/q2-itsxpress-bbmerge-error/18682/5
