### ISSUE TITLE
ITSxpress vsearch error q2-2021.11

### ISSUE THREAD

**Issue by ARW-UBT** [USDA-ARS-GBRU/q2_itsxpress#12]
Hi @arivers 
I was asked in a post at Qiime2 Forum to conact you regarding the itsxpress issue I have (https://forum.qiime2.org/t/itsxpress-vsearch-error-q2-2021-11/21947/2). 
I am not sure whethere a message sent to you via q2 forum was sent (I cannot see my message sent to you), I thought I should open a post here. 
Is there any advice from you how to get q2-itsxpress running in a fresh q2-2021.11 environment?
Best regards

**Comment by arivers** [comment]
I replied on  the qiime forum.

[https://forum.qiime2.org/t/re-itsxpress-vsearch-error-q2-2021-11/21960/2](https://forum.qiime2.org/t/re-itsxpress-vsearch-error-q2-2021-11/21960/2
)
